package com.example.campus.view

object Constance {
    const val KEY_COURSE_NAME = "key_course_name"
    const val KEY_COURSE_TEACHER_NAME = "key_course_teacher_name"
    const val KEY_COURSE_DETAIL_EDIT_FREQUENCY = "key_course_detail_detail_edit_FREQUENCY"
    const val KEY_COURSE_DETAIL_EDIT_ATTENDANCE_WAY = "key_course_detail_edit_attendance_way"
    const val KEY_COURSE_DETAIL_EDIT_EXAM_WAY = "key_course_detail_edit_exam_way"
    const val KEY_COURSE_DETAIL_EDIT_GIVEN = "key_course_detail_edit_given"
    const val KEY_COURSE_DETAIL_EDIT_SCORE = "key_course_detail_edit_score"
    const val KEY_COURSE_DETAIL_EDIT_CREDIT = "key_course_detail_edit_credit"
    const val KEY_COURSE_DETAIL_EDIT_EVALUATE = "key_course_detail_edit_evaluate"
    const val KEY_COURSE_EDIT_ADD_NAME = "key_course_edit_add_name"
    const val KEY_COURSE_EDIT_ADD_TEACHER = "key_course_edit_add_teacher"
    const val KEY_COURSE_WATCH_COUNT = "key_course_watch_count"
    const val KEY_COURSE_ID = "key_course_id"
    const val KEY_COURSE_DETAIL_GROUND_URL = "key_course_detail_ground_url"
    const val KEY_CHOSE_FALSE_OR_TRUE = "key_save_false_or_true"
    const val KEY_LOAD_NEXT_TIME = "key_load_next_time"
    const val KEY_DIALOG_TYPE_ADD_COMMENT = "key_dialog_type_add_comment"
    const val KEY_DIALOG_TYPE_ADD_CATEGORY = "key_dialog_type_add_category"
    const val KEY_COURSE_SPINNER_LAST_INDEX = "key_course_spinner_last_index"
    const val KEY_CHAT_IS_FROM_BOOK_DEAL = "key_chat_is_from_book_deal"
    const val KEY_INTENT_CHAT_NAME = "key_intent_chat_name"
    const val KEY_USER_CENTER_USER_ACCOUNT = "key_user_center_user_account"
    const val KEY_USER_CENTER_USER_NAME = "key_user_center_user_name"
    const val KEY_USER_CENTER_USER_DES = "key_user_center_user_des"
    const val KEY_USER_CENTER_USER_UNIVERSITY = "key_user_center_user_university"
    const val KEY_USER_CENTER_USER_GRADES = "key_user_center_user_grades"
    const val KEY_USER_CENTER_USER_AVATAR_URL = "key_user_center_user_avatar_url"
    const val KEY_BOOK_IMAGE_URL = "key_book_image_url"
    const val KEY_BOOK_NAME = "key_book_name"
    const val KEY_BOOK_DETAIL_LIKE_COUNT = "key_book_detail_like_count"
    const val KEY_BOOK_DEAL_AVATAR_URL = "key_book_deal_avatar_url"
    const val KEY_BOOK_DEAL_SELLER = "key_book_deal_seller"
    const val KEY_BOOK_DEAL_IMAGE_MSG = "key_book_deal_image_msg"
    const val KET_DEAL_BOOK_ID = "key_deal_book_id"
    const val KEY_BOOK_DEAL_SELLER_ID = "key_book_deal_seller_id"
    const val KEY_BOOK_DEAL_SELL_MSG = "key_book_deal_sell_msg"
    const val KEY_BOOK_DEAL_SELL_PRICE = "key_book_deal_sell_price"
    const val KEY_BOOK_DEAL_SELL_DES = "key_book_deal_sell_des"
    const val KEY_STATE_OF_LOGIN_OR_SIGN_UP = "key_state_of_login_of_sign_sign_up"
    const val KEY_REMOTE_UID = "key_remote_uid"
    const val KEY_USER_CENTER_USER_UID = "key_user_center_user_uid"
    const val KEY_REMOTE_NAME = "key_remote_NAME"
    const val KEY_REMOTE_AVATAR = "key_remote_AVATAR"
}