// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CategoryContain.proto

package com.example.campus.protoModel;

public final class CategoryContain {
  private CategoryContain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CategoryContainRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryContainRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    int getStartIndex();

    /**
     * <code>optional int32 limitCount = 2;</code>
     */
    int getLimitCount();

    /**
     * <code>optional string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>optional string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code tutorial.CategoryContainRequest}
   */
  public  static final class CategoryContainRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryContainRequest)
      CategoryContainRequestOrBuilder {
    // Use CategoryContainRequest.newBuilder() to construct.
    private CategoryContainRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryContainRequest() {
      startIndex_ = 0;
      limitCount_ = 0;
      type_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryContainRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              startIndex_ = input.readInt32();
              break;
            }
            case 16: {

              limitCount_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CategoryContain.internal_static_tutorial_CategoryContainRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CategoryContain.internal_static_tutorial_CategoryContainRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryContain.CategoryContainRequest.class, CategoryContain.CategoryContainRequest.Builder.class);
    }

    public static final int STARTINDEX_FIELD_NUMBER = 1;
    private int startIndex_;
    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    public int getStartIndex() {
      return startIndex_;
    }

    public static final int LIMITCOUNT_FIELD_NUMBER = 2;
    private int limitCount_;
    /**
     * <code>optional int32 limitCount = 2;</code>
     */
    public int getLimitCount() {
      return limitCount_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>optional string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startIndex_ != 0) {
        output.writeInt32(1, startIndex_);
      }
      if (limitCount_ != 0) {
        output.writeInt32(2, limitCount_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, startIndex_);
      }
      if (limitCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, limitCount_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryContain.CategoryContainRequest)) {
        return super.equals(obj);
      }
      CategoryContain.CategoryContainRequest other = (CategoryContain.CategoryContainRequest) obj;

      boolean result = true;
      result = result && (getStartIndex()
          == other.getStartIndex());
      result = result && (getLimitCount()
          == other.getLimitCount());
      result = result && getType()
          .equals(other.getType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STARTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getStartIndex();
      hash = (37 * hash) + LIMITCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getLimitCount();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryContain.CategoryContainRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContain.CategoryContainRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryContainRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryContainRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryContain.CategoryContainRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryContainRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryContainRequest)
        CategoryContain.CategoryContainRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CategoryContain.internal_static_tutorial_CategoryContainRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CategoryContain.internal_static_tutorial_CategoryContainRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryContain.CategoryContainRequest.class, CategoryContain.CategoryContainRequest.Builder.class);
      }

      // Construct using com.example.campus.protoModel.CategoryContain.CategoryContainRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        startIndex_ = 0;

        limitCount_ = 0;

        type_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CategoryContain.internal_static_tutorial_CategoryContainRequest_descriptor;
      }

      public CategoryContain.CategoryContainRequest getDefaultInstanceForType() {
        return CategoryContain.CategoryContainRequest.getDefaultInstance();
      }

      public CategoryContain.CategoryContainRequest build() {
        CategoryContain.CategoryContainRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryContain.CategoryContainRequest buildPartial() {
        CategoryContain.CategoryContainRequest result = new CategoryContain.CategoryContainRequest(this);
        result.startIndex_ = startIndex_;
        result.limitCount_ = limitCount_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryContain.CategoryContainRequest) {
          return mergeFrom((CategoryContain.CategoryContainRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryContain.CategoryContainRequest other) {
        if (other == CategoryContain.CategoryContainRequest.getDefaultInstance()) return this;
        if (other.getStartIndex() != 0) {
          setStartIndex(other.getStartIndex());
        }
        if (other.getLimitCount() != 0) {
          setLimitCount(other.getLimitCount());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryContain.CategoryContainRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryContain.CategoryContainRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int startIndex_ ;
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public int getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder setStartIndex(int value) {
        
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder clearStartIndex() {
        
        startIndex_ = 0;
        onChanged();
        return this;
      }

      private int limitCount_ ;
      /**
       * <code>optional int32 limitCount = 2;</code>
       */
      public int getLimitCount() {
        return limitCount_;
      }
      /**
       * <code>optional int32 limitCount = 2;</code>
       */
      public Builder setLimitCount(int value) {
        
        limitCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 limitCount = 2;</code>
       */
      public Builder clearLimitCount() {
        
        limitCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>optional string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryContainRequest)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryContainRequest)
    private static final CategoryContain.CategoryContainRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryContain.CategoryContainRequest();
    }

    public static CategoryContain.CategoryContainRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryContainRequest>
        PARSER = new com.google.protobuf.AbstractParser<CategoryContainRequest>() {
      public CategoryContainRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryContainRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryContainRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryContainRequest> getParserForType() {
      return PARSER;
    }

    public CategoryContain.CategoryContainRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CategoryContainResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryContainResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    int getStartIndex();

    /**
     * <code>optional int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>optional bool isLoadAll = 3;</code>
     */
    boolean getIsLoadAll();

    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    java.util.List<CategoryContain.CategoryResult>
        getResultsList();
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    CategoryContain.CategoryResult getResults(int index);
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    java.util.List<? extends CategoryContain.CategoryResultOrBuilder>
        getResultsOrBuilderList();
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    CategoryContain.CategoryResultOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.CategoryContainResponse}
   */
  public  static final class CategoryContainResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryContainResponse)
      CategoryContainResponseOrBuilder {
    // Use CategoryContainResponse.newBuilder() to construct.
    private CategoryContainResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryContainResponse() {
      startIndex_ = 0;
      count_ = 0;
      isLoadAll_ = false;
      results_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryContainResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              startIndex_ = input.readInt32();
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            case 24: {

              isLoadAll_ = input.readBool();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                results_ = new java.util.ArrayList<CategoryContain.CategoryResult>();
                mutable_bitField0_ |= 0x00000008;
              }
              results_.add(
                  input.readMessage(CategoryContain.CategoryResult.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CategoryContain.internal_static_tutorial_CategoryContainResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CategoryContain.internal_static_tutorial_CategoryContainResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryContain.CategoryContainResponse.class, CategoryContain.CategoryContainResponse.Builder.class);
    }

    private int bitField0_;
    public static final int STARTINDEX_FIELD_NUMBER = 1;
    private int startIndex_;
    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    public int getStartIndex() {
      return startIndex_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int ISLOADALL_FIELD_NUMBER = 3;
    private boolean isLoadAll_;
    /**
     * <code>optional bool isLoadAll = 3;</code>
     */
    public boolean getIsLoadAll() {
      return isLoadAll_;
    }

    public static final int RESULTS_FIELD_NUMBER = 4;
    private java.util.List<CategoryContain.CategoryResult> results_;
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public java.util.List<CategoryContain.CategoryResult> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public java.util.List<? extends CategoryContain.CategoryResultOrBuilder>
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public CategoryContain.CategoryResult getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public CategoryContain.CategoryResultOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startIndex_ != 0) {
        output.writeInt32(1, startIndex_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      if (isLoadAll_ != false) {
        output.writeBool(3, isLoadAll_);
      }
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(4, results_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, startIndex_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (isLoadAll_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isLoadAll_);
      }
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, results_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryContain.CategoryContainResponse)) {
        return super.equals(obj);
      }
      CategoryContain.CategoryContainResponse other = (CategoryContain.CategoryContainResponse) obj;

      boolean result = true;
      result = result && (getStartIndex()
          == other.getStartIndex());
      result = result && (getCount()
          == other.getCount());
      result = result && (getIsLoadAll()
          == other.getIsLoadAll());
      result = result && getResultsList()
          .equals(other.getResultsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STARTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getStartIndex();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + ISLOADALL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLoadAll());
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryContain.CategoryContainResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContain.CategoryContainResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryContainResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryContainResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryContain.CategoryContainResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryContainResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryContainResponse)
        CategoryContain.CategoryContainResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CategoryContain.internal_static_tutorial_CategoryContainResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CategoryContain.internal_static_tutorial_CategoryContainResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryContain.CategoryContainResponse.class, CategoryContain.CategoryContainResponse.Builder.class);
      }

      // Construct using com.example.campus.protoModel.CategoryContain.CategoryContainResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        startIndex_ = 0;

        count_ = 0;

        isLoadAll_ = false;

        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CategoryContain.internal_static_tutorial_CategoryContainResponse_descriptor;
      }

      public CategoryContain.CategoryContainResponse getDefaultInstanceForType() {
        return CategoryContain.CategoryContainResponse.getDefaultInstance();
      }

      public CategoryContain.CategoryContainResponse build() {
        CategoryContain.CategoryContainResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryContain.CategoryContainResponse buildPartial() {
        CategoryContain.CategoryContainResponse result = new CategoryContain.CategoryContainResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.startIndex_ = startIndex_;
        result.count_ = count_;
        result.isLoadAll_ = isLoadAll_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryContain.CategoryContainResponse) {
          return mergeFrom((CategoryContain.CategoryContainResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryContain.CategoryContainResponse other) {
        if (other == CategoryContain.CategoryContainResponse.getDefaultInstance()) return this;
        if (other.getStartIndex() != 0) {
          setStartIndex(other.getStartIndex());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getIsLoadAll() != false) {
          setIsLoadAll(other.getIsLoadAll());
        }
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000008);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryContain.CategoryContainResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryContain.CategoryContainResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int startIndex_ ;
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public int getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder setStartIndex(int value) {
        
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder clearStartIndex() {
        
        startIndex_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private boolean isLoadAll_ ;
      /**
       * <code>optional bool isLoadAll = 3;</code>
       */
      public boolean getIsLoadAll() {
        return isLoadAll_;
      }
      /**
       * <code>optional bool isLoadAll = 3;</code>
       */
      public Builder setIsLoadAll(boolean value) {
        
        isLoadAll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLoadAll = 3;</code>
       */
      public Builder clearIsLoadAll() {
        
        isLoadAll_ = false;
        onChanged();
        return this;
      }

      private java.util.List<CategoryContain.CategoryResult> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          results_ = new java.util.ArrayList<CategoryContain.CategoryResult>(results_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CategoryContain.CategoryResult, CategoryContain.CategoryResult.Builder, CategoryContain.CategoryResultOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public java.util.List<CategoryContain.CategoryResult> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryContain.CategoryResult getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder setResults(
          int index, CategoryContain.CategoryResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder setResults(
          int index, CategoryContain.CategoryResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(CategoryContain.CategoryResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(
          int index, CategoryContain.CategoryResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(
          CategoryContain.CategoryResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(
          int index, CategoryContain.CategoryResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends CategoryContain.CategoryResult> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryContain.CategoryResult.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryContain.CategoryResultOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public java.util.List<? extends CategoryContain.CategoryResultOrBuilder>
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryContain.CategoryResult.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            CategoryContain.CategoryResult.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryContain.CategoryResult.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, CategoryContain.CategoryResult.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public java.util.List<CategoryContain.CategoryResult.Builder>
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CategoryContain.CategoryResult, CategoryContain.CategoryResult.Builder, CategoryContain.CategoryResultOrBuilder>
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CategoryContain.CategoryResult, CategoryContain.CategoryResult.Builder, CategoryContain.CategoryResultOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryContainResponse)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryContainResponse)
    private static final CategoryContain.CategoryContainResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryContain.CategoryContainResponse();
    }

    public static CategoryContain.CategoryContainResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryContainResponse>
        PARSER = new com.google.protobuf.AbstractParser<CategoryContainResponse>() {
      public CategoryContainResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryContainResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryContainResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryContainResponse> getParserForType() {
      return PARSER;
    }

    public CategoryContain.CategoryContainResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CategoryResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string courseName = 1;</code>
     */
    java.lang.String getCourseName();
    /**
     * <code>optional string courseName = 1;</code>
     */
    com.google.protobuf.ByteString
        getCourseNameBytes();

    /**
     * <code>optional string courseGrades = 2;</code>
     */
    java.lang.String getCourseGrades();
    /**
     * <code>optional string courseGrades = 2;</code>
     */
    com.google.protobuf.ByteString
        getCourseGradesBytes();

    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    java.lang.String getCourseTeacher();
    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    com.google.protobuf.ByteString
        getCourseTeacherBytes();

    /**
     * <code>optional string courseType = 4;</code>
     */
    java.lang.String getCourseType();
    /**
     * <code>optional string courseType = 4;</code>
     */
    com.google.protobuf.ByteString
        getCourseTypeBytes();
  }
  /**
   * Protobuf type {@code tutorial.CategoryResult}
   */
  public  static final class CategoryResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryResult)
      CategoryResultOrBuilder {
    // Use CategoryResult.newBuilder() to construct.
    private CategoryResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryResult() {
      courseName_ = "";
      courseGrades_ = "";
      courseTeacher_ = "";
      courseType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              courseName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              courseGrades_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              courseTeacher_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              courseType_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CategoryContain.internal_static_tutorial_CategoryResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CategoryContain.internal_static_tutorial_CategoryResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryContain.CategoryResult.class, CategoryContain.CategoryResult.Builder.class);
    }

    public static final int COURSENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object courseName_;
    /**
     * <code>optional string courseName = 1;</code>
     */
    public java.lang.String getCourseName() {
      java.lang.Object ref = courseName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCourseNameBytes() {
      java.lang.Object ref = courseName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSEGRADES_FIELD_NUMBER = 2;
    private volatile java.lang.Object courseGrades_;
    /**
     * <code>optional string courseGrades = 2;</code>
     */
    public java.lang.String getCourseGrades() {
      java.lang.Object ref = courseGrades_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseGrades_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseGrades = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCourseGradesBytes() {
      java.lang.Object ref = courseGrades_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseGrades_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSETEACHER_FIELD_NUMBER = 3;
    private volatile java.lang.Object courseTeacher_;
    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    public java.lang.String getCourseTeacher() {
      java.lang.Object ref = courseTeacher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseTeacher_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCourseTeacherBytes() {
      java.lang.Object ref = courseTeacher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseTeacher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSETYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object courseType_;
    /**
     * <code>optional string courseType = 4;</code>
     */
    public java.lang.String getCourseType() {
      java.lang.Object ref = courseType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCourseTypeBytes() {
      java.lang.Object ref = courseType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCourseNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, courseName_);
      }
      if (!getCourseGradesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, courseGrades_);
      }
      if (!getCourseTeacherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, courseTeacher_);
      }
      if (!getCourseTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, courseType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCourseNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, courseName_);
      }
      if (!getCourseGradesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, courseGrades_);
      }
      if (!getCourseTeacherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, courseTeacher_);
      }
      if (!getCourseTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, courseType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryContain.CategoryResult)) {
        return super.equals(obj);
      }
      CategoryContain.CategoryResult other = (CategoryContain.CategoryResult) obj;

      boolean result = true;
      result = result && getCourseName()
          .equals(other.getCourseName());
      result = result && getCourseGrades()
          .equals(other.getCourseGrades());
      result = result && getCourseTeacher()
          .equals(other.getCourseTeacher());
      result = result && getCourseType()
          .equals(other.getCourseType());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COURSENAME_FIELD_NUMBER;
      hash = (53 * hash) + getCourseName().hashCode();
      hash = (37 * hash) + COURSEGRADES_FIELD_NUMBER;
      hash = (53 * hash) + getCourseGrades().hashCode();
      hash = (37 * hash) + COURSETEACHER_FIELD_NUMBER;
      hash = (53 * hash) + getCourseTeacher().hashCode();
      hash = (37 * hash) + COURSETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCourseType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryContain.CategoryResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContain.CategoryResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContain.CategoryResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContain.CategoryResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContain.CategoryResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContain.CategoryResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContain.CategoryResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContain.CategoryResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryContain.CategoryResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryResult)
        CategoryContain.CategoryResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CategoryContain.internal_static_tutorial_CategoryResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CategoryContain.internal_static_tutorial_CategoryResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryContain.CategoryResult.class, CategoryContain.CategoryResult.Builder.class);
      }

      // Construct using com.example.campus.protoModel.CategoryContain.CategoryResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        courseName_ = "";

        courseGrades_ = "";

        courseTeacher_ = "";

        courseType_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CategoryContain.internal_static_tutorial_CategoryResult_descriptor;
      }

      public CategoryContain.CategoryResult getDefaultInstanceForType() {
        return CategoryContain.CategoryResult.getDefaultInstance();
      }

      public CategoryContain.CategoryResult build() {
        CategoryContain.CategoryResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryContain.CategoryResult buildPartial() {
        CategoryContain.CategoryResult result = new CategoryContain.CategoryResult(this);
        result.courseName_ = courseName_;
        result.courseGrades_ = courseGrades_;
        result.courseTeacher_ = courseTeacher_;
        result.courseType_ = courseType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryContain.CategoryResult) {
          return mergeFrom((CategoryContain.CategoryResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryContain.CategoryResult other) {
        if (other == CategoryContain.CategoryResult.getDefaultInstance()) return this;
        if (!other.getCourseName().isEmpty()) {
          courseName_ = other.courseName_;
          onChanged();
        }
        if (!other.getCourseGrades().isEmpty()) {
          courseGrades_ = other.courseGrades_;
          onChanged();
        }
        if (!other.getCourseTeacher().isEmpty()) {
          courseTeacher_ = other.courseTeacher_;
          onChanged();
        }
        if (!other.getCourseType().isEmpty()) {
          courseType_ = other.courseType_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryContain.CategoryResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryContain.CategoryResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object courseName_ = "";
      /**
       * <code>optional string courseName = 1;</code>
       */
      public java.lang.String getCourseName() {
        java.lang.Object ref = courseName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          courseName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCourseNameBytes() {
        java.lang.Object ref = courseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          courseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public Builder setCourseName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public Builder clearCourseName() {
        
        courseName_ = getDefaultInstance().getCourseName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public Builder setCourseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object courseGrades_ = "";
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public java.lang.String getCourseGrades() {
        java.lang.Object ref = courseGrades_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          courseGrades_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCourseGradesBytes() {
        java.lang.Object ref = courseGrades_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          courseGrades_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public Builder setCourseGrades(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseGrades_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public Builder clearCourseGrades() {
        
        courseGrades_ = getDefaultInstance().getCourseGrades();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public Builder setCourseGradesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseGrades_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object courseTeacher_ = "";
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public java.lang.String getCourseTeacher() {
        java.lang.Object ref = courseTeacher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          courseTeacher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCourseTeacherBytes() {
        java.lang.Object ref = courseTeacher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          courseTeacher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public Builder setCourseTeacher(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseTeacher_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public Builder clearCourseTeacher() {
        
        courseTeacher_ = getDefaultInstance().getCourseTeacher();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public Builder setCourseTeacherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseTeacher_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object courseType_ = "";
      /**
       * <code>optional string courseType = 4;</code>
       */
      public java.lang.String getCourseType() {
        java.lang.Object ref = courseType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          courseType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCourseTypeBytes() {
        java.lang.Object ref = courseType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          courseType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public Builder setCourseType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public Builder clearCourseType() {
        
        courseType_ = getDefaultInstance().getCourseType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public Builder setCourseTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryResult)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryResult)
    private static final CategoryContain.CategoryResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryContain.CategoryResult();
    }

    public static CategoryContain.CategoryResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryResult>
        PARSER = new com.google.protobuf.AbstractParser<CategoryResult>() {
      public CategoryResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryResult> getParserForType() {
      return PARSER;
    }

    public CategoryContain.CategoryResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryContainRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryContainRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryContainResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryContainResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CategoryContain.proto\022\010tutorial\"N\n\026Cat" +
      "egoryContainRequest\022\022\n\nstartIndex\030\001 \001(\005\022" +
      "\022\n\nlimitCount\030\002 \001(\005\022\014\n\004type\030\003 \001(\t\"z\n\027Cat" +
      "egoryContainResponse\022\022\n\nstartIndex\030\001 \001(\005" +
      "\022\r\n\005count\030\002 \001(\005\022\021\n\tisLoadAll\030\003 \001(\010\022)\n\007re" +
      "sults\030\004 \003(\0132\030.tutorial.CategoryResult\"e\n" +
      "\016CategoryResult\022\022\n\ncourseName\030\001 \001(\t\022\024\n\014c" +
      "ourseGrades\030\002 \001(\t\022\025\n\rcourseTeacher\030\003 \001(\t" +
      "\022\022\n\ncourseType\030\004 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_CategoryContainRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_CategoryContainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryContainRequest_descriptor,
        new java.lang.String[] { "StartIndex", "LimitCount", "Type", });
    internal_static_tutorial_CategoryContainResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_CategoryContainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryContainResponse_descriptor,
        new java.lang.String[] { "StartIndex", "Count", "IsLoadAll", "Results", });
    internal_static_tutorial_CategoryResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_CategoryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryResult_descriptor,
        new java.lang.String[] { "CourseName", "CourseGrades", "CourseTeacher", "CourseType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
