// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CategoryResponse.proto

package com.example.campus.protoModel;

public final class CategoryResponseOuterClass {
  private CategoryResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CategoryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string currentSchool = 1;</code>
     */
    java.lang.String getCurrentSchool();
    /**
     * <code>optional string currentSchool = 1;</code>
     */
    com.google.protobuf.ByteString
        getCurrentSchoolBytes();

    /**
     * <code>optional int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>repeated string category = 3;</code>
     */
    java.util.List<java.lang.String>
        getCategoryList();
    /**
     * <code>repeated string category = 3;</code>
     */
    int getCategoryCount();
    /**
     * <code>repeated string category = 3;</code>
     */
    java.lang.String getCategory(int index);
    /**
     * <code>repeated string category = 3;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.CategoryResponse}
   */
  public  static final class CategoryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryResponse)
      CategoryResponseOrBuilder {
    // Use CategoryResponse.newBuilder() to construct.
    private CategoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryResponse() {
      currentSchool_ = "";
      count_ = 0;
      category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currentSchool_ = s;
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                category_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              category_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          category_ = category_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CategoryResponseOuterClass.internal_static_tutorial_CategoryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CategoryResponseOuterClass.internal_static_tutorial_CategoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryResponseOuterClass.CategoryResponse.class, CategoryResponseOuterClass.CategoryResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CURRENTSCHOOL_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentSchool_;
    /**
     * <code>optional string currentSchool = 1;</code>
     */
    public java.lang.String getCurrentSchool() {
      java.lang.Object ref = currentSchool_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentSchool_ = s;
        return s;
      }
    }
    /**
     * <code>optional string currentSchool = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentSchoolBytes() {
      java.lang.Object ref = currentSchool_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentSchool_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList category_;
    /**
     * <code>repeated string category = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCategoryList() {
      return category_;
    }
    /**
     * <code>repeated string category = 3;</code>
     */
    public int getCategoryCount() {
      return category_.size();
    }
    /**
     * <code>repeated string category = 3;</code>
     */
    public java.lang.String getCategory(int index) {
      return category_.get(index);
    }
    /**
     * <code>repeated string category = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes(int index) {
      return category_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrentSchoolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentSchool_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      for (int i = 0; i < category_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, category_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrentSchoolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentSchool_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < category_.size(); i++) {
          dataSize += computeStringSizeNoTag(category_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCategoryList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryResponseOuterClass.CategoryResponse)) {
        return super.equals(obj);
      }
      CategoryResponseOuterClass.CategoryResponse other = (CategoryResponseOuterClass.CategoryResponse) obj;

      boolean result = true;
      result = result && getCurrentSchool()
          .equals(other.getCurrentSchool());
      result = result && (getCount()
          == other.getCount());
      result = result && getCategoryList()
          .equals(other.getCategoryList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CURRENTSCHOOL_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentSchool().hashCode();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      if (getCategoryCount() > 0) {
        hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getCategoryList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryResponseOuterClass.CategoryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryResponseOuterClass.CategoryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryResponseOuterClass.CategoryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryResponse)
        CategoryResponseOuterClass.CategoryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CategoryResponseOuterClass.internal_static_tutorial_CategoryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CategoryResponseOuterClass.internal_static_tutorial_CategoryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryResponseOuterClass.CategoryResponse.class, CategoryResponseOuterClass.CategoryResponse.Builder.class);
      }

      // Construct using com.example.campus.protoModel.CategoryResponseOuterClass.CategoryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        currentSchool_ = "";

        count_ = 0;

        category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CategoryResponseOuterClass.internal_static_tutorial_CategoryResponse_descriptor;
      }

      public CategoryResponseOuterClass.CategoryResponse getDefaultInstanceForType() {
        return CategoryResponseOuterClass.CategoryResponse.getDefaultInstance();
      }

      public CategoryResponseOuterClass.CategoryResponse build() {
        CategoryResponseOuterClass.CategoryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryResponseOuterClass.CategoryResponse buildPartial() {
        CategoryResponseOuterClass.CategoryResponse result = new CategoryResponseOuterClass.CategoryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.currentSchool_ = currentSchool_;
        result.count_ = count_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          category_ = category_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.category_ = category_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryResponseOuterClass.CategoryResponse) {
          return mergeFrom((CategoryResponseOuterClass.CategoryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryResponseOuterClass.CategoryResponse other) {
        if (other == CategoryResponseOuterClass.CategoryResponse.getDefaultInstance()) return this;
        if (!other.getCurrentSchool().isEmpty()) {
          currentSchool_ = other.currentSchool_;
          onChanged();
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (!other.category_.isEmpty()) {
          if (category_.isEmpty()) {
            category_ = other.category_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCategoryIsMutable();
            category_.addAll(other.category_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryResponseOuterClass.CategoryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryResponseOuterClass.CategoryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object currentSchool_ = "";
      /**
       * <code>optional string currentSchool = 1;</code>
       */
      public java.lang.String getCurrentSchool() {
        java.lang.Object ref = currentSchool_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentSchool_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string currentSchool = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCurrentSchoolBytes() {
        java.lang.Object ref = currentSchool_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentSchool_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string currentSchool = 1;</code>
       */
      public Builder setCurrentSchool(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentSchool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string currentSchool = 1;</code>
       */
      public Builder clearCurrentSchool() {
        
        currentSchool_ = getDefaultInstance().getCurrentSchool();
        onChanged();
        return this;
      }
      /**
       * <code>optional string currentSchool = 1;</code>
       */
      public Builder setCurrentSchoolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentSchool_ = value;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCategoryIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          category_ = new com.google.protobuf.LazyStringArrayList(category_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCategoryList() {
        return category_.getUnmodifiableView();
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public int getCategoryCount() {
        return category_.size();
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public java.lang.String getCategory(int index) {
        return category_.get(index);
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes(int index) {
        return category_.getByteString(index);
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public Builder setCategory(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoryIsMutable();
        category_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public Builder addCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoryIsMutable();
        category_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public Builder addAllCategory(
          java.lang.Iterable<java.lang.String> values) {
        ensureCategoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, category_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public Builder clearCategory() {
        category_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string category = 3;</code>
       */
      public Builder addCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCategoryIsMutable();
        category_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryResponse)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryResponse)
    private static final CategoryResponseOuterClass.CategoryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryResponseOuterClass.CategoryResponse();
    }

    public static CategoryResponseOuterClass.CategoryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryResponse>
        PARSER = new com.google.protobuf.AbstractParser<CategoryResponse>() {
      public CategoryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CategoryResponse> getParserForType() {
      return PARSER;
    }

    public CategoryResponseOuterClass.CategoryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026CategoryResponse.proto\022\010tutorial\"J\n\020Ca" +
      "tegoryResponse\022\025\n\rcurrentSchool\030\001 \001(\t\022\r\n" +
      "\005count\030\002 \001(\005\022\020\n\010category\030\003 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_CategoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_CategoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryResponse_descriptor,
        new java.lang.String[] { "CurrentSchool", "Count", "Category", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
