// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CourseContain.proto

package com.example.campus.protoModel;

public final class CourseContain {
  private CourseContain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CategoryContainRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryContainRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    int getStartIndex();

    /**
     * <code>optional int32 limitCount = 2;</code>
     */
    int getLimitCount();

    /**
     * <code>optional string type = 3;</code>
     */
    String getType();
    /**
     * <code>optional string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code tutorial.CategoryContainRequest}
   */
  public  static final class CategoryContainRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryContainRequest)
      CategoryContainRequestOrBuilder {
    // Use CategoryContainRequest.newBuilder() to construct.
    private CategoryContainRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryContainRequest() {
      startIndex_ = 0;
      limitCount_ = 0;
      type_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryContainRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              startIndex_ = input.readInt32();
              break;
            }
            case 16: {

              limitCount_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CourseContain.internal_static_tutorial_CategoryContainRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CourseContain.internal_static_tutorial_CategoryContainRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryContainRequest.class, Builder.class);
    }

    public static final int STARTINDEX_FIELD_NUMBER = 1;
    private int startIndex_;
    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    public int getStartIndex() {
      return startIndex_;
    }

    public static final int LIMITCOUNT_FIELD_NUMBER = 2;
    private int limitCount_;
    /**
     * <code>optional int32 limitCount = 2;</code>
     */
    public int getLimitCount() {
      return limitCount_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile Object type_;
    /**
     * <code>optional string type = 3;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>optional string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startIndex_ != 0) {
        output.writeInt32(1, startIndex_);
      }
      if (limitCount_ != 0) {
        output.writeInt32(2, limitCount_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, startIndex_);
      }
      if (limitCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, limitCount_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryContainRequest)) {
        return super.equals(obj);
      }
      CategoryContainRequest other = (CategoryContainRequest) obj;

      boolean result = true;
      result = result && (getStartIndex()
          == other.getStartIndex());
      result = result && (getLimitCount()
          == other.getLimitCount());
      result = result && getType()
          .equals(other.getType());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STARTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getStartIndex();
      hash = (37 * hash) + LIMITCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getLimitCount();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryContainRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContainRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContainRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContainRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContainRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContainRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContainRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryContainRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContainRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContainRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryContainRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryContainRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryContainRequest)
        CategoryContainRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CourseContain.internal_static_tutorial_CategoryContainRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CourseContain.internal_static_tutorial_CategoryContainRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryContainRequest.class, Builder.class);
      }

      // Construct using tutorial.CourseContain.CategoryContainRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        startIndex_ = 0;

        limitCount_ = 0;

        type_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CourseContain.internal_static_tutorial_CategoryContainRequest_descriptor;
      }

      public CategoryContainRequest getDefaultInstanceForType() {
        return CategoryContainRequest.getDefaultInstance();
      }

      public CategoryContainRequest build() {
        CategoryContainRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryContainRequest buildPartial() {
        CategoryContainRequest result = new CategoryContainRequest(this);
        result.startIndex_ = startIndex_;
        result.limitCount_ = limitCount_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryContainRequest) {
          return mergeFrom((CategoryContainRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryContainRequest other) {
        if (other == CategoryContainRequest.getDefaultInstance()) return this;
        if (other.getStartIndex() != 0) {
          setStartIndex(other.getStartIndex());
        }
        if (other.getLimitCount() != 0) {
          setLimitCount(other.getLimitCount());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryContainRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryContainRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int startIndex_ ;
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public int getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder setStartIndex(int value) {
        
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder clearStartIndex() {
        
        startIndex_ = 0;
        onChanged();
        return this;
      }

      private int limitCount_ ;
      /**
       * <code>optional int32 limitCount = 2;</code>
       */
      public int getLimitCount() {
        return limitCount_;
      }
      /**
       * <code>optional int32 limitCount = 2;</code>
       */
      public Builder setLimitCount(int value) {
        
        limitCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 limitCount = 2;</code>
       */
      public Builder clearLimitCount() {
        
        limitCount_ = 0;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>optional string type = 3;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryContainRequest)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryContainRequest)
    private static final CategoryContainRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryContainRequest();
    }

    public static CategoryContainRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryContainRequest>
        PARSER = new com.google.protobuf.AbstractParser<CategoryContainRequest>() {
      public CategoryContainRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryContainRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryContainRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CategoryContainRequest> getParserForType() {
      return PARSER;
    }

    public CategoryContainRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CategoryContainResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryContainResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    int getStartIndex();

    /**
     * <code>optional int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>optional bool isLoadAll = 3;</code>
     */
    boolean getIsLoadAll();

    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    java.util.List<CategoryResult>
        getResultsList();
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    CategoryResult getResults(int index);
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    java.util.List<? extends CategoryResultOrBuilder>
        getResultsOrBuilderList();
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    CategoryResultOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.CategoryContainResponse}
   */
  public  static final class CategoryContainResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryContainResponse)
      CategoryContainResponseOrBuilder {
    // Use CategoryContainResponse.newBuilder() to construct.
    private CategoryContainResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryContainResponse() {
      startIndex_ = 0;
      count_ = 0;
      isLoadAll_ = false;
      results_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryContainResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              startIndex_ = input.readInt32();
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            case 24: {

              isLoadAll_ = input.readBool();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                results_ = new java.util.ArrayList<CategoryResult>();
                mutable_bitField0_ |= 0x00000008;
              }
              results_.add(
                  input.readMessage(CategoryResult.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CourseContain.internal_static_tutorial_CategoryContainResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CourseContain.internal_static_tutorial_CategoryContainResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryContainResponse.class, Builder.class);
    }

    private int bitField0_;
    public static final int STARTINDEX_FIELD_NUMBER = 1;
    private int startIndex_;
    /**
     * <code>optional int32 startIndex = 1;</code>
     */
    public int getStartIndex() {
      return startIndex_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int ISLOADALL_FIELD_NUMBER = 3;
    private boolean isLoadAll_;
    /**
     * <code>optional bool isLoadAll = 3;</code>
     */
    public boolean getIsLoadAll() {
      return isLoadAll_;
    }

    public static final int RESULTS_FIELD_NUMBER = 4;
    private java.util.List<CategoryResult> results_;
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public java.util.List<CategoryResult> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public java.util.List<? extends CategoryResultOrBuilder>
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public CategoryResult getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .tutorial.CategoryResult results = 4;</code>
     */
    public CategoryResultOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startIndex_ != 0) {
        output.writeInt32(1, startIndex_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      if (isLoadAll_ != false) {
        output.writeBool(3, isLoadAll_);
      }
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(4, results_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, startIndex_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (isLoadAll_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isLoadAll_);
      }
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, results_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryContainResponse)) {
        return super.equals(obj);
      }
      CategoryContainResponse other = (CategoryContainResponse) obj;

      boolean result = true;
      result = result && (getStartIndex()
          == other.getStartIndex());
      result = result && (getCount()
          == other.getCount());
      result = result && (getIsLoadAll()
          == other.getIsLoadAll());
      result = result && getResultsList()
          .equals(other.getResultsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STARTINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getStartIndex();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + ISLOADALL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLoadAll());
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryContainResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContainResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContainResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryContainResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryContainResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContainResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContainResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryContainResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryContainResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryContainResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryContainResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryContainResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryContainResponse)
        CategoryContainResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CourseContain.internal_static_tutorial_CategoryContainResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CourseContain.internal_static_tutorial_CategoryContainResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryContainResponse.class, Builder.class);
      }

      // Construct using tutorial.CourseContain.CategoryContainResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        startIndex_ = 0;

        count_ = 0;

        isLoadAll_ = false;

        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CourseContain.internal_static_tutorial_CategoryContainResponse_descriptor;
      }

      public CategoryContainResponse getDefaultInstanceForType() {
        return CategoryContainResponse.getDefaultInstance();
      }

      public CategoryContainResponse build() {
        CategoryContainResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryContainResponse buildPartial() {
        CategoryContainResponse result = new CategoryContainResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.startIndex_ = startIndex_;
        result.count_ = count_;
        result.isLoadAll_ = isLoadAll_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryContainResponse) {
          return mergeFrom((CategoryContainResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryContainResponse other) {
        if (other == CategoryContainResponse.getDefaultInstance()) return this;
        if (other.getStartIndex() != 0) {
          setStartIndex(other.getStartIndex());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getIsLoadAll() != false) {
          setIsLoadAll(other.getIsLoadAll());
        }
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000008);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryContainResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryContainResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int startIndex_ ;
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public int getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder setStartIndex(int value) {
        
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 startIndex = 1;</code>
       */
      public Builder clearStartIndex() {
        
        startIndex_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private boolean isLoadAll_ ;
      /**
       * <code>optional bool isLoadAll = 3;</code>
       */
      public boolean getIsLoadAll() {
        return isLoadAll_;
      }
      /**
       * <code>optional bool isLoadAll = 3;</code>
       */
      public Builder setIsLoadAll(boolean value) {
        
        isLoadAll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLoadAll = 3;</code>
       */
      public Builder clearIsLoadAll() {
        
        isLoadAll_ = false;
        onChanged();
        return this;
      }

      private java.util.List<CategoryResult> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          results_ = new java.util.ArrayList<CategoryResult>(results_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CategoryResult, CategoryResult.Builder, CategoryResultOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public java.util.List<CategoryResult> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryResult getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder setResults(
          int index, CategoryResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder setResults(
          int index, CategoryResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(CategoryResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(
          int index, CategoryResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(
          CategoryResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addResults(
          int index, CategoryResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder addAllResults(
          Iterable<? extends CategoryResult> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryResult.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryResultOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public java.util.List<? extends CategoryResultOrBuilder>
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryResult.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            CategoryResult.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public CategoryResult.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, CategoryResult.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.CategoryResult results = 4;</code>
       */
      public java.util.List<CategoryResult.Builder>
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CategoryResult, CategoryResult.Builder, CategoryResultOrBuilder>
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CategoryResult, CategoryResult.Builder, CategoryResultOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryContainResponse)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryContainResponse)
    private static final CategoryContainResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryContainResponse();
    }

    public static CategoryContainResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryContainResponse>
        PARSER = new com.google.protobuf.AbstractParser<CategoryContainResponse>() {
      public CategoryContainResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryContainResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryContainResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CategoryContainResponse> getParserForType() {
      return PARSER;
    }

    public CategoryContainResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CategoryResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CategoryResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string courseName = 1;</code>
     */
    String getCourseName();
    /**
     * <code>optional string courseName = 1;</code>
     */
    com.google.protobuf.ByteString
        getCourseNameBytes();

    /**
     * <code>optional string courseGrades = 2;</code>
     */
    String getCourseGrades();
    /**
     * <code>optional string courseGrades = 2;</code>
     */
    com.google.protobuf.ByteString
        getCourseGradesBytes();

    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    String getCourseTeacher();
    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    com.google.protobuf.ByteString
        getCourseTeacherBytes();

    /**
     * <code>optional string courseType = 4;</code>
     */
    String getCourseType();
    /**
     * <code>optional string courseType = 4;</code>
     */
    com.google.protobuf.ByteString
        getCourseTypeBytes();

    /**
     * <code>optional int64 courseId = 5;</code>
     */
    long getCourseId();

    /**
     * <code>optional int32 watcherCount = 6;</code>
     */
    int getWatcherCount();

    /**
     * <code>optional string backgroundURL = 7;</code>
     */
    String getBackgroundURL();
    /**
     * <code>optional string backgroundURL = 7;</code>
     */
    com.google.protobuf.ByteString
        getBackgroundURLBytes();
  }
  /**
   * Protobuf type {@code tutorial.CategoryResult}
   */
  public  static final class CategoryResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CategoryResult)
      CategoryResultOrBuilder {
    // Use CategoryResult.newBuilder() to construct.
    private CategoryResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CategoryResult() {
      courseName_ = "";
      courseGrades_ = "";
      courseTeacher_ = "";
      courseType_ = "";
      courseId_ = 0L;
      watcherCount_ = 0;
      backgroundURL_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CategoryResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              courseName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              courseGrades_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              courseTeacher_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              courseType_ = s;
              break;
            }
            case 40: {

              courseId_ = input.readInt64();
              break;
            }
            case 48: {

              watcherCount_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              backgroundURL_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CourseContain.internal_static_tutorial_CategoryResult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CourseContain.internal_static_tutorial_CategoryResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CategoryResult.class, Builder.class);
    }

    public static final int COURSENAME_FIELD_NUMBER = 1;
    private volatile Object courseName_;
    /**
     * <code>optional string courseName = 1;</code>
     */
    public String getCourseName() {
      Object ref = courseName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        courseName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCourseNameBytes() {
      Object ref = courseName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        courseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSEGRADES_FIELD_NUMBER = 2;
    private volatile Object courseGrades_;
    /**
     * <code>optional string courseGrades = 2;</code>
     */
    public String getCourseGrades() {
      Object ref = courseGrades_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        courseGrades_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseGrades = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCourseGradesBytes() {
      Object ref = courseGrades_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        courseGrades_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSETEACHER_FIELD_NUMBER = 3;
    private volatile Object courseTeacher_;
    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    public String getCourseTeacher() {
      Object ref = courseTeacher_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        courseTeacher_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseTeacher = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCourseTeacherBytes() {
      Object ref = courseTeacher_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        courseTeacher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSETYPE_FIELD_NUMBER = 4;
    private volatile Object courseType_;
    /**
     * <code>optional string courseType = 4;</code>
     */
    public String getCourseType() {
      Object ref = courseType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        courseType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string courseType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCourseTypeBytes() {
      Object ref = courseType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        courseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSEID_FIELD_NUMBER = 5;
    private long courseId_;
    /**
     * <code>optional int64 courseId = 5;</code>
     */
    public long getCourseId() {
      return courseId_;
    }

    public static final int WATCHERCOUNT_FIELD_NUMBER = 6;
    private int watcherCount_;
    /**
     * <code>optional int32 watcherCount = 6;</code>
     */
    public int getWatcherCount() {
      return watcherCount_;
    }

    public static final int BACKGROUNDURL_FIELD_NUMBER = 7;
    private volatile Object backgroundURL_;
    /**
     * <code>optional string backgroundURL = 7;</code>
     */
    public String getBackgroundURL() {
      Object ref = backgroundURL_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        backgroundURL_ = s;
        return s;
      }
    }
    /**
     * <code>optional string backgroundURL = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBackgroundURLBytes() {
      Object ref = backgroundURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        backgroundURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCourseNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, courseName_);
      }
      if (!getCourseGradesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, courseGrades_);
      }
      if (!getCourseTeacherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, courseTeacher_);
      }
      if (!getCourseTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, courseType_);
      }
      if (courseId_ != 0L) {
        output.writeInt64(5, courseId_);
      }
      if (watcherCount_ != 0) {
        output.writeInt32(6, watcherCount_);
      }
      if (!getBackgroundURLBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, backgroundURL_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCourseNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, courseName_);
      }
      if (!getCourseGradesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, courseGrades_);
      }
      if (!getCourseTeacherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, courseTeacher_);
      }
      if (!getCourseTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, courseType_);
      }
      if (courseId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, courseId_);
      }
      if (watcherCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, watcherCount_);
      }
      if (!getBackgroundURLBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, backgroundURL_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CategoryResult)) {
        return super.equals(obj);
      }
      CategoryResult other = (CategoryResult) obj;

      boolean result = true;
      result = result && getCourseName()
          .equals(other.getCourseName());
      result = result && getCourseGrades()
          .equals(other.getCourseGrades());
      result = result && getCourseTeacher()
          .equals(other.getCourseTeacher());
      result = result && getCourseType()
          .equals(other.getCourseType());
      result = result && (getCourseId()
          == other.getCourseId());
      result = result && (getWatcherCount()
          == other.getWatcherCount());
      result = result && getBackgroundURL()
          .equals(other.getBackgroundURL());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COURSENAME_FIELD_NUMBER;
      hash = (53 * hash) + getCourseName().hashCode();
      hash = (37 * hash) + COURSEGRADES_FIELD_NUMBER;
      hash = (53 * hash) + getCourseGrades().hashCode();
      hash = (37 * hash) + COURSETEACHER_FIELD_NUMBER;
      hash = (53 * hash) + getCourseTeacher().hashCode();
      hash = (37 * hash) + COURSETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCourseType().hashCode();
      hash = (37 * hash) + COURSEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCourseId());
      hash = (37 * hash) + WATCHERCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getWatcherCount();
      hash = (37 * hash) + BACKGROUNDURL_FIELD_NUMBER;
      hash = (53 * hash) + getBackgroundURL().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CategoryResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CategoryResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CategoryResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CategoryResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CategoryResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CategoryResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CategoryResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CategoryResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CategoryResult)
        CategoryResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CourseContain.internal_static_tutorial_CategoryResult_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CourseContain.internal_static_tutorial_CategoryResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CategoryResult.class, Builder.class);
      }

      // Construct using tutorial.CourseContain.CategoryResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        courseName_ = "";

        courseGrades_ = "";

        courseTeacher_ = "";

        courseType_ = "";

        courseId_ = 0L;

        watcherCount_ = 0;

        backgroundURL_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CourseContain.internal_static_tutorial_CategoryResult_descriptor;
      }

      public CategoryResult getDefaultInstanceForType() {
        return CategoryResult.getDefaultInstance();
      }

      public CategoryResult build() {
        CategoryResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CategoryResult buildPartial() {
        CategoryResult result = new CategoryResult(this);
        result.courseName_ = courseName_;
        result.courseGrades_ = courseGrades_;
        result.courseTeacher_ = courseTeacher_;
        result.courseType_ = courseType_;
        result.courseId_ = courseId_;
        result.watcherCount_ = watcherCount_;
        result.backgroundURL_ = backgroundURL_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CategoryResult) {
          return mergeFrom((CategoryResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CategoryResult other) {
        if (other == CategoryResult.getDefaultInstance()) return this;
        if (!other.getCourseName().isEmpty()) {
          courseName_ = other.courseName_;
          onChanged();
        }
        if (!other.getCourseGrades().isEmpty()) {
          courseGrades_ = other.courseGrades_;
          onChanged();
        }
        if (!other.getCourseTeacher().isEmpty()) {
          courseTeacher_ = other.courseTeacher_;
          onChanged();
        }
        if (!other.getCourseType().isEmpty()) {
          courseType_ = other.courseType_;
          onChanged();
        }
        if (other.getCourseId() != 0L) {
          setCourseId(other.getCourseId());
        }
        if (other.getWatcherCount() != 0) {
          setWatcherCount(other.getWatcherCount());
        }
        if (!other.getBackgroundURL().isEmpty()) {
          backgroundURL_ = other.backgroundURL_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CategoryResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CategoryResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object courseName_ = "";
      /**
       * <code>optional string courseName = 1;</code>
       */
      public String getCourseName() {
        Object ref = courseName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          courseName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCourseNameBytes() {
        Object ref = courseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          courseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public Builder setCourseName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public Builder clearCourseName() {
        
        courseName_ = getDefaultInstance().getCourseName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseName = 1;</code>
       */
      public Builder setCourseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseName_ = value;
        onChanged();
        return this;
      }

      private Object courseGrades_ = "";
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public String getCourseGrades() {
        Object ref = courseGrades_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          courseGrades_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCourseGradesBytes() {
        Object ref = courseGrades_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          courseGrades_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public Builder setCourseGrades(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseGrades_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public Builder clearCourseGrades() {
        
        courseGrades_ = getDefaultInstance().getCourseGrades();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseGrades = 2;</code>
       */
      public Builder setCourseGradesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseGrades_ = value;
        onChanged();
        return this;
      }

      private Object courseTeacher_ = "";
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public String getCourseTeacher() {
        Object ref = courseTeacher_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          courseTeacher_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCourseTeacherBytes() {
        Object ref = courseTeacher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          courseTeacher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public Builder setCourseTeacher(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseTeacher_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public Builder clearCourseTeacher() {
        
        courseTeacher_ = getDefaultInstance().getCourseTeacher();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseTeacher = 3;</code>
       */
      public Builder setCourseTeacherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseTeacher_ = value;
        onChanged();
        return this;
      }

      private Object courseType_ = "";
      /**
       * <code>optional string courseType = 4;</code>
       */
      public String getCourseType() {
        Object ref = courseType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          courseType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCourseTypeBytes() {
        Object ref = courseType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          courseType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public Builder setCourseType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public Builder clearCourseType() {
        
        courseType_ = getDefaultInstance().getCourseType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string courseType = 4;</code>
       */
      public Builder setCourseTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseType_ = value;
        onChanged();
        return this;
      }

      private long courseId_ ;
      /**
       * <code>optional int64 courseId = 5;</code>
       */
      public long getCourseId() {
        return courseId_;
      }
      /**
       * <code>optional int64 courseId = 5;</code>
       */
      public Builder setCourseId(long value) {
        
        courseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 courseId = 5;</code>
       */
      public Builder clearCourseId() {
        
        courseId_ = 0L;
        onChanged();
        return this;
      }

      private int watcherCount_ ;
      /**
       * <code>optional int32 watcherCount = 6;</code>
       */
      public int getWatcherCount() {
        return watcherCount_;
      }
      /**
       * <code>optional int32 watcherCount = 6;</code>
       */
      public Builder setWatcherCount(int value) {
        
        watcherCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 watcherCount = 6;</code>
       */
      public Builder clearWatcherCount() {
        
        watcherCount_ = 0;
        onChanged();
        return this;
      }

      private Object backgroundURL_ = "";
      /**
       * <code>optional string backgroundURL = 7;</code>
       */
      public String getBackgroundURL() {
        Object ref = backgroundURL_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          backgroundURL_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string backgroundURL = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBackgroundURLBytes() {
        Object ref = backgroundURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          backgroundURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string backgroundURL = 7;</code>
       */
      public Builder setBackgroundURL(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        backgroundURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string backgroundURL = 7;</code>
       */
      public Builder clearBackgroundURL() {
        
        backgroundURL_ = getDefaultInstance().getBackgroundURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string backgroundURL = 7;</code>
       */
      public Builder setBackgroundURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        backgroundURL_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CategoryResult)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CategoryResult)
    private static final CategoryResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CategoryResult();
    }

    public static CategoryResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CategoryResult>
        PARSER = new com.google.protobuf.AbstractParser<CategoryResult>() {
      public CategoryResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CategoryResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CategoryResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CategoryResult> getParserForType() {
      return PARSER;
    }

    public CategoryResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryContainRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryContainRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryContainResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryContainResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CategoryResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CategoryResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023CourseContain.proto\022\010tutorial\"N\n\026Categ" +
      "oryContainRequest\022\022\n\nstartIndex\030\001 \001(\005\022\022\n" +
      "\nlimitCount\030\002 \001(\005\022\014\n\004type\030\003 \001(\t\"z\n\027Categ" +
      "oryContainResponse\022\022\n\nstartIndex\030\001 \001(\005\022\r" +
      "\n\005count\030\002 \001(\005\022\021\n\tisLoadAll\030\003 \001(\010\022)\n\007resu" +
      "lts\030\004 \003(\0132\030.tutorial.CategoryResult\"\244\001\n\016" +
      "CategoryResult\022\022\n\ncourseName\030\001 \001(\t\022\024\n\014co" +
      "urseGrades\030\002 \001(\t\022\025\n\rcourseTeacher\030\003 \001(\t\022" +
      "\022\n\ncourseType\030\004 \001(\t\022\020\n\010courseId\030\005 \001(\003\022\024\n" +
      "\014watcherCount\030\006 \001(\005\022\025\n\rbackgroundURL\030\007 \001",
      "(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_CategoryContainRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_CategoryContainRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryContainRequest_descriptor,
        new String[] { "StartIndex", "LimitCount", "Type", });
    internal_static_tutorial_CategoryContainResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_CategoryContainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryContainResponse_descriptor,
        new String[] { "StartIndex", "Count", "IsLoadAll", "Results", });
    internal_static_tutorial_CategoryResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_CategoryResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CategoryResult_descriptor,
        new String[] { "CourseName", "CourseGrades", "CourseTeacher", "CourseType", "CourseId", "WatcherCount", "BackgroundURL", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
